name: Advanced Coverage Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  # Run weekly
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight on Sunday
  workflow_dispatch:

jobs:
  coverage:
    name: Run Advanced Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: hongjr03/tinymist-coverage-workflow@v0.1.2
        with:
          # Use latest Tinymist version
          tinymist_version: 'latest'
          # Analyze multiple files
          target_files: 'main.typ,docs/guide.typ,examples/demo.typ'
          # Custom report path
          report_path: 'docs/coverage-reports'
          # Only update badge in README.md
          readme_paths: 'README.md'
        env:
          # Optional: Use custom token for committing changes
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}