name: Basic Coverage Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    name: Run Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: hongjr03/tinymist-coverage-workflow@v0.1.2
        with:
          # Just use the default settings
          target_files: 'README.typ'