name: Coverage Analysis Without Typship

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    name: Run Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: hongjr03/tinymist-coverage-workflow@v0.1.2
        with:
          # Disable typship development environment setup
          setup_typship: false
          # Analyze single file
          target_files: 'document.typ'
          # Disable auto commit
          auto_commit: false